language: node_js
node_js:
  - "8"
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
  - pip install --user awscli
  - pip install --user aws-sam-cli
script:
  - sam validate --template template.json
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
