language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - pip install --user awscli
  - pip install --user aws-sam-cli
script:
  - sam validate --template template.json
  - ./scripts/build.sh
deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
